version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - /Users/udayshankarreddy/Rolec/Repo/nginx_reverse_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
